### ISSUE TITLE
missing dependency containerd.io for fedora 29 aarch64

### ISSUE THREAD

**Issue by andrasi** [docker/docker-install#107]
After trying to install the latest nightly of docker-ce on a Raspberry Pi 3 running Fedora 29 it seems that a dependency is not satisfied:

`nothing provides containerd.io needed by docker-ce-3:0.0.0.20190323130520.1618664-0.fc29.aarch64`

How can I get docker-ce running on my Pi?

Thank you!

**Comment by thaJeztah** [comment]
Closing as Fedora 29 reached EOL, and trying to use the script should now print a deprecation error; https://github.com/docker/docker-install/blob/dd4d114074ecd649c37aa17e688c55fbd4c032fb/install.sh#L485-L489
