### ISSUE TITLE
rootless: move to 19.03 by default

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker-install#112]
We have 19.03 (test) tarballs of rootless extras now. The install script should start defaulting to that now, with a possibility to switch `CHANNEL` between nightly, test and stable.

https://download.docker.com/linux/static/test/x86_64/

@AkihiroSuda

**Comment by zelahi** [comment]
@tonistiigi I took a small pass at this.  I hope it works or if there are any required changes, I would love your feedback!!

**Comment by AkihiroSuda** [comment]
can we move this forward?

**Comment by AkihiroSuda** [comment]
https://get.docker.com/rootless now defaults to 19.03.5. This issue is fixed.

**Comment by StefanScherer** [comment]
Thanks for confirming.
