### ISSUE TITLE
unable to install docker ce for ubuntu 18.04

### ISSUE THREAD

**Issue by fc373745** [docker/docker-install#113]
`curl -fsSL get.docker.com | sh`

gives me 
```
+ sudo -E sh -c apt-get update -qq >/dev/null
E: The repository 'http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu bionic Release' does not have a Release file.

```

**Comment by nemchik** [comment]
That's a generic apt issue.

Run `sudo nano /etc/apt/sources.list` and comment or remove the line for that repo.

**Comment by mikeyEcology** [comment]
Thank you @nemchik . I tried to do this for a similar error, but I don't have the package in `/etc/apt/sources.list`. The package that's throwing the error for me is ffmpeg.
