### ISSUE TITLE
docker:  error starting docker

### ISSUE THREAD

**Issue by CarlotaVina** [docker/docker-install#114]
I try to start docker with

sudo systemctl start docker
I get the error 
Error starting daemon: error initializing graphdriver: /var/lib/docker contains several valid graphdrivers: devicemapper, overl

I tried to configure devicemapper. I created the file /etc/docker/daemon.json and I configured with 

{
  "storage-driver": "devicemapper",
  "storage-opts": [
    "dm.directlvm_device=/dev/xdf",
    "dm.thinp_percent=95",
    "dm.thinp_metapercent=1",
    "dm.thinp_autoextend_threshold=80",
    "dm.thinp_autoextend_percent=20",
    "dm.directlvm_device_force=false"
  ]
}

I get an error in line  dm.directlvm_device=/dev/xdf" when I start docker. After that I deleted the file/etc/docker/daemon.json

And now, I get this error.
How can I fix this issue?

**Comment by thaJeztah** [comment]
I'm closing this ticket as it went stale, and this looks to be an issue in the environment in which it was run (containing ambiguous previous storage drivers); device mapper is now also deprecated and removed from docker.
