### ISSUE TITLE
Option to install compose

### ISSUE THREAD

**Issue by Ben-Atherton** [docker/docker-install#117]
Could this script be expanded to install compose at the same time? maybe as an optional flag?

**Comment by nemchik** [comment]
There's a few different ways to install compose. I've personally written a script to install docker using this script and compose via python pip. I'd be curious to see an official implementation, but that might warrant it's own separate script to keep this clean for those who just want docker-ce.

**Comment by nemchik** [comment]
It seems like there are now official packages in the docker-ce repos https://download.docker.com/linux/ for the new compose v2 plugin. It would be great to see those packages added by default (or at least optionally) to this install script. This is mentioned by 
@thaJeztah in https://github.com/docker/roadmap/issues/257#issuecomment-1067025381

**Comment by thaJeztah** [comment]
Yes, the compose plugin is now installed by default since https://github.com/docker/docker-install/pull/288, so closing this ticket
