### ISSUE TITLE
Support CentOS 6

### ISSUE THREAD

**Issue by vipera7** [docker/docker-install#122]
I've tested the script on CentOS 6 and it look like it ain't supported.

Error message : 
```
# Executing docker install script, commit: UNKNOWN

ERROR: Unsupported distribution ''


```

We can get older redhat version in the following file : 

`/etc/redhat-release`

**Comment by nemchik** [comment]
It looks like https://download.docker.com/linux/centos/ has no downloads for 6 and https://download.docker.com/linux/ does not list plain redhat. Of course you can probably install from source, but that's not what this script does.

**Comment by nemchik** [comment]
Also, just an FYI according to https://wiki.centos.org/About/Product CentOS 6 will be EOL in just a little over a year (initial release having been in 2010). I don't know if Docker will decide to put up packages for CentOS 6 at this point, but who knows.

**Comment by seemethere** [comment]
There are currently no plans to support CentOS / RHEL 6
