### ISSUE TITLE
Support Ubuntu 19.04 (Disco)

### ISSUE THREAD

**Issue by o-alquimista** [docker/docker-install#130]
It is missing from the list, so the script halts on Ubuntu 19.04

**Comment by iosvanyd1** [comment]
For me it fails as well. Expect it seems to be a mismatch between the expected file size and the actual file size.

`E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/disco/stable/binary-amd64/Packages.bz2  File has unexpected size (3466 != 2422). Mirror sync in progress? [IP: 13.226.42.129 443]`

**Comment by iosvanyd1** [comment]
Also fails if I try to install using 
`sudo add-apt-repository \
>    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
>    $(lsb_release -cs) \
>    stable"`

it outputs:
`Err:5 https://download.docker.com/linux/ubuntu disco/stable amd64 Packages     
  File has unexpected size (3466 != 2422). Mirror sync in progress?
`

**Comment by nemchik** [comment]
Disco should be working as a stable release was first published on 10-10-2019.

@iosvanyd1 your issue is slightly different, and is affecting more than just Disco. I've got the same error using Bionic.

**Comment by iosvanyd1** [comment]
@nemchik any idea of when and how this will be resolved?

**Comment by nemchik** [comment]
Seems to be working for me on a system I held off on previously so that system did not experience the issue.

I'm having other troubles with the system I'd seen the issue on before, but the overall problem may be resolved.

**Comment by seemethere** [comment]
This should already work. Closing for now...
