### ISSUE TITLE
how to change the default docker registry from docker.io to my private registry?

### ISSUE THREAD

**Issue by damozhiying** [docker/docker-install#133]
how to change the default docker registry from docker.io to my private registry?
i had config daemon.json or docker.service, not take effect, the harbor port is 7080,
@ywk253100  thanks a lot,
now i have one problem,docker not pull image from private mirror but from docker.io,
![image](https://user-images.githubusercontent.com/10277950/61506078-8db41280-aa13-11e9-8404-0deff31dec5b.png)
![image](https://user-images.githubusercontent.com/10277950/61506088-97d61100-aa13-11e9-99e8-7cce9f06acb1.png)
![image](https://user-images.githubusercontent.com/10277950/61506100-a3293c80-aa13-11e9-9a72-2ab128999cf3.png)

**Comment by thaJeztah** [comment]
closing as stale, and off-topic for this repository
