### ISSUE TITLE
Broken link in rootless-install.sh

### ISSUE THREAD

**Issue by rasai** [docker/docker-install#135]
Hello,

I was trying to install the rootless version of docker by following blog post:
https://engineering.docker.com/2019/02/experimenting-with-rootless-docker/
(I know it is half a year old now, but I could not find other instructions on installation)

Unfortunately, the script fails with:
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

I dug in to the script a bit and it looks like the issue is coming from line 316 in rootless-install.sh:
```
curl -L -o rootless.tgz "$STATIC_RELEASE_ROOTLESS_URL"
```
because  https://master.dockerproject.org/linux/x86_64/docker-rootless-extras.tgz no longer exists, and instead is returning an XML file with the contents.
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>linux/x86_64/docker-rootless-extras.tgz</Key><RequestId>520E9920358F8BDB</RequestId><HostId>38sHuvfQtiXDKtenebEICJXhpyGdLj0GLQ5gcw8WZUlGh38JONd0Vc0cuHQtrHrJmiE853DJqRo=</HostId></Error>
```
And the tar commands following it is throwing out the original error. I took a quick look around https://master.dockerproject.org/ but I could not figure out what to replace it with.

**Comment by seemethere** [comment]
No that is correct, looking into this issue today.

**Comment by Shiki-H** [comment]
I encountered exactly the same problem and by chance, I found this source:
https://download.docker.com/linux/static/stable/x86_64/

However, I was not able to start the container successfully and encountered the following error:

```
[rootlesskit:parent] error: failed to setup UID/GID map: newuidmap 17168 [0 682 1 1 100000 65536] failed: newuidmap: write to uid_map failed: Operation not permitted
: exit status 1
```

**Comment by AkihiroSuda** [comment]
@Shiki-H see https://github.com/rootless-containers/rootlesskit#requirements

**Comment by AkihiroSuda** [comment]
Close?

**Comment by StefanScherer** [comment]
Yes, it‘s fixed.  closing now.
