### ISSUE TITLE
https://get.docker.com/rootless is not synced with this repo

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker-install#141]
#99 seems not applied to https://get.docker.com/rootless as of writing this

@tonistiigi @seemethere

**Comment by mike2307** [comment]
Good luck getting a reply here... I ran into the same. See https://github.com/docker/docker-install/issues/137#issuecomment-532704440

**Comment by AkihiroSuda** [comment]
It's synced now, thanks
