### ISSUE TITLE
How to docker run with rootless behind porxy?

### ISSUE THREAD

**Issue by huyu398** [docker/docker-install#150]
## Problem
Rootless docker is installed following commands on my system.
```bash
$ export http_proxy=http://proxy_ip:proxy_port/
$ export https_proxy=http://proxy_ip:proxy_port/
$ curl -fsSL https://get.docker.com/rootless | sh
$ echo export PATH=/home/d043635/bin:$PATH >> ~/.bashrc
$ echo export DOCKER_HOST=unix:///run/user/1001/docker.sock >> ~/.bashrc
$ source ~/.bashrc
```
And I add proxy config(`Environment=http_proxy=http://proxy_ip:proxy_port`) to `~/.config/systemd/user/docker.service`.
I checked setting proxy config with `docker info`.
ButI got following error with `docker run hello-world`.
```
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp proxy_ip:proxy_port: connect: connection refused.
See 'docker run --help'.
```
Where is wrong setteing?

## Environment
* Ubuntu 18.04 LTS
* Docker version is `Docker version master-dockerproject-2019-12-10, build 08eaead2`
* proxy is cntlm on localhost (so, proxy_ip is localhost, and proxy_port is 3128)

Thank you

**Comment by AkihiroSuda** [comment]
localhost is unsupported

**Comment by AkihiroSuda** [comment]
Ports listening on `localhost` can be accessible from `dockerd` as 192.168.65.2 (VPNKit) or 10.0.2.2 (slirp4netns).

But you need to remove `--disable-host-loopback` flag for `rootlesskit` in `~/bin/dockerd-rootless.sh`: https://github.com/moby/moby/blob/1347481b9eb53c30f820df42a146aab8d06a7340/contrib/dockerd-rootless.sh#L85

**Comment by huyu398** [comment]
@AkihiroSuda 
1. Change `localhost` to `192.168.65.2` at `Environment=http_proxy` of `~/.config/systemd/user/docker.service`.
2. Remove `--disable-host-loopback` flag in `~/bin/docerd-rootless.sh`.
3. Restart docker daemon with `systemctrl --user daemon-reload` and `systemctrl --user restart docker`
With above settings, `docker run hello-world` is successed.

Thank you for your advices!

**Comment by ktdharan** [comment]
does this solution still work  ? -> https://github.com/docker/docker-install/issues/150#issuecomment-564958165 

when trying on redhat 8 replacing the proxy with 10.0.2.2  for the slirp4netns gives an 

"proxyconnect tcp: dial tcp 10.0.2.2:3128: connect: network is unreachable " 

if we try giving the 192.168.65.2 as proxy we get " net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
"

/user.slice/user-100.slice/user@100.service/docker.service
           ├─753426 rootlesskit --net=slirp4netns --mtu=65521 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=slirp4netns --copy-up=/etc --copy-u>
           ├─753438 /proc/self/exe --net=slirp4netns --mtu=65521 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=slirp4netns --copy-up=/etc --cop>
           ├─753453 slirp4netns --mtu 65521 -r 3 --disable-host-loopback --api-socket /tmp/rootlesskit2736572894/.s4nn.sock --enable-sandbox --enable-seccomp 753438 tap0
           ├─753460 dockerd --iptables=false
           └─753477 containerd --config /run/user/100/docker/containerd/containerd.toml --log-level info
@AkihiroSuda

**Comment by AkihiroSuda** [comment]
> crashes the docker Deamon

Could you provide logs

**Comment by Wubmm** [comment]
It worked, thanks! It took me days to realize that i should use 10.0.2.2 instead of 192.168.65.2 (systemctl --user status docker).
