### ISSUE TITLE
Support for CentOS 8 

### ISSUE THREAD

**Issue by snowdream** [docker/docker-install#154]
Please add Support for CentOS 8 ,Thank you.

**Comment by AkihiroSuda** [comment]
Work is progress in  https://github.com/docker/docker-ce-packaging/pull/416

**Comment by jakues** [comment]
![Screenshot_20200613-151750](https://user-images.githubusercontent.com/34295920/84563890-13a61e00-ad89-11ea-8979-e62b16c14bb3.png)

**Comment by thaJeztah** [comment]
closing as centos 8 is now EOL
