### ISSUE TITLE
How to uninstall Docker Rootless mode ?

### ISSUE THREAD

**Issue by maxiqboy** [docker/docker-install#166]
I'm new for the town, so I'm sorry to ask something stupid,

I cannot uninstall Docker Rootless mode, 

I try `sudo apt-get remove docker docker-engine docker.io containerd runc` but it not working,

I don't know how to do because it's still new and there is not so much document or article about that,

Thanks

**Comment by thaJeztah** [comment]
Rootless install doesn't use the `apt` packages (as those can only be installed globally, and as such require `root` / `sudo` to install). Instead, it uses static binaries, and installs them inside your home directory (in `$HOME/bin/`).

We should probably add some documentation about uninstalling those (/cc @AkihiroSuda)

**Comment by AkihiroSuda** [comment]
Probably we should add uninstaller to https://github.com/moby/moby/issues/40707

**Comment by AkihiroSuda** [comment]
The current uninstall steps:
```
$ rootlesskit rm -rf ~/.local/share/docker
$ cd ~/bin
$ rm -f *docker* *containerd* *runc* *rootlesskit* *vpnkit*

**Comment by maxiqboy** [comment]
@thaJeztah  @AkihiroSuda  thank you guys for the quick reply, I will try to find out

**Comment by maxiqboy** [comment]
Now I got the bigger problem, I cannot install a normal docker,

it keeps saying that : "ERROR: Cannot connect to the Docker daemon at unix:///run/user/1000/docker.sock. Is the docker daemon running?"

maybe after removing Docker Rootless mode, it still not come back to normal?

```bash
sudo setfacl -m user:bastian:rw /var/run/docker.sock
 docker ps                                           
Cannot connect to the Docker daemon at unix:///run/user/1000/docker.sock. Is the docker daemon running?
 sudo gpasswd -a $USER docker                        
Adding user bastian to group docker
 sudo setfacl -m user:bastian:rw /var/run/docker.sock
 docker ps
Cannot connect to the Docker daemon at unix:///run/user/1000/docker.sock. Is the docker daemon running?
 sudo setfacl -m user:bastian:rw /var/run/user/1000/docker.sock
setfacl: /var/run/user/1000/docker.sock: No such file or directory
 ✘  ~ 
 sudo setfacl -m user:bastian:rw /run/user/1000/docker.sock 
setfacl: /run/user/1000/docker.sock: No such file or directory
 ✘  ~ 
 systemctl start docker                                    
 ~ 
 docker ps
Cannot connect to the Docker daemon at unix:///run/user/1000/docker.sock. Is the docker daemon running?
 docker ps
Cannot connect to the Docker daemon at unix:///run/user/1000/docker.sock. Is the docker daemon running?
 docker info                                   
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///run/user/1000/docker.sock. Is the docker daemon running?
errors pretty printing info

```

**Comment by AkihiroSuda** [comment]
Probably you have added `DOCKER_HOST` in your `.bashrc`

**Comment by maxiqboy** [comment]
finally, I just found out on rootless docs:  https://docs.docker.com/engine/security/rootless/

```bash
# Make sure the following environment variables are set (or add them to ~/.bashrc):
export DOCKER_HOST=unix:///run/user/1001/docker.sock
```

So I went to my file (~/.zshrc ) to remove that line, and after logout/login, my docker has finally work, thank god

**Comment by shubhamrajvanshi** [comment]
Documenting for Ubuntu 20.04.2 LTS users
I had to run below steps 
`rootlesskit rm -rf ~/.local/share/docker`
`systemctl --user stop docker`

remove `export DOCKER_HOST=unix:///run/user/1001/docker.sock from ` from .bashrc and logout and login

**Comment by davidkhala** [comment]
I believe this will be more appropriate
```
dockerd-rootless-setuptool.sh uninstall
```

**Comment by rdolezel** [comment]
Linux newbie here. Hard way to find rootless docker does not support macvlan (or I am not able to get it working).

My uninstall procedure:
sudo nano /etc/sysctl.conf      # remove added line
nano ~/.bashrc         # remove added lines
sudo loginctl disable-linger $(whoami)
systemctl --user stop docker.service
sudo rm /var/run/docker.sock              # no idea why it was here but it was blocking the next command
/usr/bin/dockerd-rootless-setuptool.sh uninstall
/usr/bin/rootlesskit rm -rf /home/radek/.local/share/docker
exit                     # log out & log in
sudo apt remove uidmap docker-ce-rootless-extras

**Comment by xome** [comment]
When you followed all the steps and still have the context "rootless" with `docker info`, but "default" with `sudo docker info`, then check if you have the directory `~/.docker` and remove it
