### ISSUE TITLE
Failed to start containerd: timeout waiting for containerd to start, dockerd-rootless.sh

### ISSUE THREAD

**Issue by VasilyRakche** [docker/docker-install#168]
I can not start docker daemon. Running `sudo docker run hello-world` gives output:
```
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```
System is Ubuntu 18.04.  
I was following installation guide on website, everything worked fine. I was able to configure rootless also following [this](https://docs.docker.com/engine/security/rootless/).   
After trying to run a container, I got an error: **Error response from daemon: driver failed programming external connectivity on endpoint**  
As suggested in issue [#2722](https://github.com/docker/for-win/issues/2722) I restarted docker and it worked. However it appeared again with another image, and now docker is not starting.  
Running ```systemctl status docker.service``` gives following output:
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-04-25 12:40:55 CEST; 13min ago
     Docs: https://docs.docker.com
  Process: 8815 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 8815 (code=exited, status=1/FAILURE)

Apr 25 12:40:55 vasko-XPS-15-9560 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Apr 25 12:40:55 vasko-XPS-15-9560 systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Apr 25 12:40:55 vasko-XPS-15-9560 systemd[1]: Stopped Docker Application Container Engine.
Apr 25 12:40:55 vasko-XPS-15-9560 systemd[1]: docker.service: Start request repeated too quickly.
Apr 25 12:40:55 vasko-XPS-15-9560 systemd[1]: docker.service: Failed with result 'exit-code'.
Apr 25 12:40:55 vasko-XPS-15-9560 systemd[1]: Failed to start Docker Application Container Engine.
```

I dont know what to do, dont have much experience with docker.

**Comment by mantasdaskev** [comment]
so what did you do? I have the same problem
