### ISSUE TITLE
getting warning apt-key parsing

### ISSUE THREAD

**Issue by LukasWestholt** [docker/docker-install#188]
Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-42-generic x86_64)

_Warning_
sudo -E sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)

in
`$sh_c "curl -fsSL \"$DOWNLOAD_URL/linux/$lsb_dist/gpg\" | apt-key add -qq - >/dev/null"`

**Comment by thaJeztah** [comment]
closing; I think this should be fixed by https://github.com/docker/docker-install/pull/391
