### ISSUE TITLE
Missing SHA

### ISSUE THREAD

**Issue by ccarse** [docker/docker-install#20]
Reading https://get.docker.com/ and trying to find the commit it was built from. It says it was built from 29533f9 but I can't seem to find that. Is this a case of some git history that's been rewritten possibly? 

Thanks

**Comment by seemethere** [comment]
@ccarse 
`https://github.com/docker/docker-install/commit/29533f927cc6136955486b655506eec18c198e80`?

**Comment by seemethere** [comment]
It's also the short version of the sha, you can view the repo from that point with a:

```shell
git checkout 29533f9
```
