### ISSUE TITLE
Fails to install on Ubuntu 16.04 - Unable to run apt-get update

### ISSUE THREAD

**Issue by philrumble-fz** [docker/docker-install#205]
I ran 
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh

and it fails with 

+ sh -c apt-get update -qq >/dev/null
W: The repository 'https://download.docker.com/linux/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/xenial/stable/binary-amd64/Packages  
E: Some index files failed to download. They have been ignored, or old ones used instead.

The file /etc/apt/sources.list contains, which matches the documentation.

deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

**Comment by thaJeztah** [comment]
closing as ubuntu 16.04 (xenial) reached EOL, and should now produce a deprecation warning / error; https://github.com/docker/docker-install/pull/238
