### ISSUE TITLE
install.sh (rootful): update "If you would like to use Docker as a non-root user, you should now consider ..." text

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker-install#210]
https://github.com/docker/docker-install/blob/9dd5b52ae6ab9f316f59e828fbd75986df30b3e5/install.sh#L143-L155

This seems outdated. Guide for rootless mode should be appended or prepended here.

**Comment by StefanScherer** [comment]
But this message is shown after the user did eg. `curl https://get.docker.com | sh` and already installed everything. Isn't it too late to suggest to use the other script instead? 🤔 

(Should we put a general sleep 20 in this script and advertise the rootless script maybe? 😄 )

**Comment by AkihiroSuda** [comment]
This needs https://github.com/docker/docker-install/issues/212 (`deb: install docker-ce-rootless-extras automatically`)

**Comment by AkihiroSuda** [comment]
opened https://github.com/docker/docker-install/pull/215
