### ISSUE TITLE
deb: install docker-ce-rootless-extras automatically

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker-install#212]
Currently `docker-ce-rootelss-extras` is automatically installed on RPM distros but not installed on deb distros.

This is because [the deb spec does not specify `docker-ce-rootless-extras` as a hard dependency](https://github.com/docker/docker-ce-packaging/blob/4865d0386b312294a2a6f8dc5a0ed0bfbfff862c/deb/common/control#L37), while [the RPM spec specifies it as a hard dependency](https://github.com/docker/docker-ce-packaging/blob/4865d0386b312294a2a6f8dc5a0ed0bfbfff862c/rpm/SPECS/docker-ce.spec#L22). 

Thanks to @konstruktoid  for reporting this: https://github.com/docker/roadmap/issues/188

## Plan A
Remove `--no-install-recommends` https://github.com/docker/docker-install/blob/9dd5b52ae6ab9f316f59e828fbd75986df30b3e5/install.sh#L406

## Plan B
Add `docker-ce-rootless-extras$pkg_version` to this line:
https://github.com/docker/docker-install/blob/9dd5b52ae6ab9f316f59e828fbd75986df30b3e5/install.sh#L406

We may also want to add `slirp4netns` (>= 0.4.0) here because we do not have VPNkit in the deb package.
But `slirp4netns` (>= 0.4.0) deb is not available for Ubuntu 18.04 and Debian 10.
https://github.com/docker/docker-ce-packaging/blob/4865d0386b312294a2a6f8dc5a0ed0bfbfff862c/deb/common/control#L90
## Plan C
Move `docker-ce-rootless-extras` from `Recommends` to `Depends`: https://github.com/docker/docker-ce-packaging/blob/4865d0386b312294a2a6f8dc5a0ed0bfbfff862c/deb/common/control#L37

**Comment by AkihiroSuda** [comment]
@StefanScherer @thaJeztah @tianon @justincormack WDYT?

**Comment by thaJeztah** [comment]
Of the above options, I'm slightly in favor of plan "b". Option "a" seems too "course", and I prefer "explicit > implicit".

If we want to allow the script to be used in a more "tailored" fashion, we could consider adding an env-var to "opt-out" of installing the rootless packages (if it doesn't complicate the script too much)

> We may also want to add slirp4netns (>= 0.4.0) here 

Hmm... yes, that's a tricky one; I guess that would make install fail if the distro doesn't have it, correct? And I guess `vpnkit` is not a package on any mainstream distro, so we can't make it a `Requires slirp4netns | vpnkit`; https://github.com/docker/docker-ce-packaging/blob/3f2b79d/deb/common/control#L90

> while the RPM spec specifies it as a hard dependency.

I think this is a limitation of RPM (at least the versions on CentOS/RHEL 7) that it lacks the possibility to define "soft" dependencies.

Keeping it as "recommends" allows users to be more specific as to what they want to install (as this dependency won't be needed if you run a rootful installation, which would probably still be the most common setup in server situations).

**Comment by soinu** [comment]
Plan A and B look good to me, I don't like plan C because on a rootful only installation you actually don't depend on any rootless packages.

**Comment by thaJeztah** [comment]
Option B has the advantage that it helps for "update" scenarios (given: the script was not strictly "designed" for that, but I know there's quite some users that use if for that purpose as well; see https://github.com/docker/docker-install/pull/195 for a discussion related to that)

**Comment by tianon** [comment]
Honestly, it was hugely surprising to me when I discovered that `docker-ce-rootless-extras` was even in `Recommends:` (and thus tried to install by default in any properly configured Debian-based distribution).

I would've expected `Suggests:`, which does *not* install by default.

Quoting the relevant bits from https://www.debian.org/doc/debian-policy/ch-relationships.html#binary-dependencies-depends-recommends-suggests-enhances-pre-depends:

> `Recommends`
> > This declares a strong, but not absolute, dependency.
> >
> > The `Recommends` field should list packages that would be found together with this one in all but unusual installations.

> `Suggests`
> > This is used to declare that one package may be more useful with one or more others. Using this field tells the packaging system and the user that the listed packages are related to this one and can perhaps enhance its usefulness, but that installing this one without them is perfectly reasonable.

I can say without a doubt that `Depends:` is not correct:

> `Depends`
> > This declares an absolute dependency. A package will not be configured unless all of the packages listed in its `Depends` field have been correctly configured (unless there is a circular dependency as described above).
> >
> > The `Depends` field should be used if the depended-on package is required for the depending package to provide a significant amount of functionality.

**Comment by AkihiroSuda** [comment]
opened PR https://github.com/docker/docker-install/pull/215 to install `docker-ce-rootless-extras` explicitly

@tianon I feel "Recommends: This declares a strong, but not absolute, dependency." is the best fit for `docker-ce-rootless-extras`.

**Comment by tianon** [comment]
> ... packages that would be found together with this one in all but unusual installations.

This really doesn't seem to fit, though.  Most users will still be root installs.
