### ISSUE TITLE
https://get.docker.com/ is out of sync with this repo

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker-install#219]
https://get.docker.com/ seems out of sync since commit 3d8fe77c2c46c5b7571f94b42793905e5b3e42e4

**Comment by AkihiroSuda** [comment]
@StefanScherer @tiborvass @thaJeztah Could you retrigger the syncing script?

**Comment by StefanScherer** [comment]
Thanks @AkihiroSuda !
I've triggered the Jenkins job.

**Comment by AkihiroSuda** [comment]
Thanks!
