### ISSUE TITLE
How to update docker version? (Updating from script fails, and no instructions at link provided)

### ISSUE THREAD

**Issue by MarkErik** [docker/docker-install#226]
I am currently running docker 20.10.5 and I would like to update to the latest released version (20.10.6).

I couldn't find any instructions on how to update the version, so I tried to run the install script, however it fails and presents the following message:
```
mark@vultr:~$ curl -fsSL https://get.docker.com/rootless | sh
# Installing stable version 20.10.6
# Existing rootless Docker detected at /home/mark/bin/dockerd
# See https://docs.docker.com/go/rootless/ for the usage.
```

I went to the link however I couldn't find anything about updating the software. 

From another post I saw the following commands suggested:
```
systemctl --user stop docker.service
systemctl --user disable docker.service
```
However, after running the above 2 commands, when I tried to run the installation script again, it still gave me the same error.

Thank you for any help and apologies if I missed the instructions for how to update the docker version.

**Comment by AkihiroSuda** [comment]
Upgrade step:

```console
$ systemctl --user stop docker
$ rm -f ~/bin/dockerd
$ curl -fsSL https://get.docker.com/rootless | sh
```


https://github.com/moby/moby/issues/42301#issuecomment-822307001
