### ISSUE TITLE
Docker pull fails

### ISSUE THREAD

**Issue by anilknayak** [docker/docker-install#267]
Query:
```
docker run -d --name=grafana -p 3000:3000 grafana/grafana-enterprise:6.7.2-ubuntu
```
```
docker --version
Docker version 20.10.11, build dea9396
```

```
OS: Ubuntu 18.04

```

Error:
```
docker: failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header.
See 'docker run --help'.
```

**Comment by thaJeztah** [comment]
Closing as off-topic for this issue tracker (which is for tracking bugs in the get.docker.com install script). For support / other type of questions, consider using one of;

- the [Discussione](https://github.com/moby/moby/discussions) on the Moby repository
- the [Docker community Slack channel](https://dockr.ly/comm-slack)
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)
- the Docker Support Forums - https://forums.docker.com
