### ISSUE TITLE
Docker cannot be downloaded due to debian version 11

### ISSUE THREAD

**Issue by vedimuthan** [docker/docker-install#270]
Hi,

We have an issue downloading docker through https://test.docker.com/ script. Please see the Dockerfile content below. When i do "cat /etc/debian_version", it shows 11.2. But if you look at the actual script, there is no logic for version 11. I could see it is only checking for version 8, 9 and 10. we are getting "**The repository 'https://download.docker.com/linux/debian 11 Release' does not have a Release file**" error. Can you please fix this issue?

```docker
FROM python:3.7

RUN apt-get update -y \
 && apt-get install -y \
        gnupg \
        gnupg2 \
 && apt-get clean

RUN pip install pip==20.2.3

# install docker
RUN cat /etc/debian_version
RUN curl -fsSL https://test.docker.com/ | sh
```

![image](https://user-images.githubusercontent.com/53485013/151433196-24dcca79-5794-4123-9eca-10825b8189b5.png)
![image](https://user-images.githubusercontent.com/53485013/151434643-4bf726fe-19cb-495f-9dcf-9f49a0023117.png)
![image](https://user-images.githubusercontent.com/53485013/151433739-6ba9a62e-03d5-4337-a616-093b50009c77.png)

**Comment by thaJeztah** [comment]
This should be fixed through https://github.com/docker/docker-install/pull/243
