### ISSUE TITLE
Rootless docker installation issue on Ubuntu18 (after updates done on 21st March)

### ISSUE THREAD

**Issue by Priyanshu-xcde** [docker/docker-install#282]
Hi, after some updates that were done in rootless docker on 21st March, I'm seeing an issue installing rootless docker on Ubuntu1-8.

We didn't see this error back in February 2022, and on rootless docker page nothing is mentioned about this issue. We did not see this message earlier during February on the same Ubuntu-18 vm that we are using now

`+ PATH=/home/pipelinesRootless/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin /home/pipelinesRootless/bin/dockerd-rootless-setuptool.sh install`
`[INFO] systemd not detected, dockerd-rootless.sh needs to be started manually:`

`PATH=/home/pipelinesRootless/bin:/sbin:/usr/sbin:$PATH dockerd-rootless.sh `

Full error logs:

`root@ubuntu-bionic:/home/vagrant# sudo -E -u tempRootlessUser ./script.sh`
`# Installing stable version 20.10.12`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                 Dload  Upload   Total   Spent    Left  Speed`
`100 60.4M  100 60.4M    0     0  6354k      0  0:00:09  0:00:09 --:--:-- 6783k`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                 Dload  Upload   Total   Spent    Left  Speed`
`100 18.0M  100 18.0M    0     0  6157k      0  0:00:03  0:00:03 --:--:-- 6157k`
`+ PATH=/home/tempRootlessUser/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin` `/home/tempRootlessUser/bin/dockerd-rootless-setuptool.sh install`
`[INFO] systemd not detected, dockerd-rootless.sh needs to be started manually:`

`PATH=/home/tempRootlessUser/bin:/sbin:/usr/sbin:$PATH dockerd-rootless.sh `

`[INFO] Creating CLI context "rootless"`
`Successfully created context "rootless"`

`[INFO] Make sure the following environment variables are set (or add them to ~/.bashrc):`

`# WARNING: systemd not found. You have to remove XDG_RUNTIME_DIR manually on every logout.`
`export XDG_RUNTIME_DIR=/home/tempRootlessUser/.docker/run`
`export PATH=/home/tempRootlessUser/bin:$PATH`
`export DOCKER_HOST=unix:///home/tempRootlessUser/.docker/run/docker.sock`

Can someone please take a look and let me know what we're missing here?

**Comment by thaJeztah** [comment]
The INFO log comes from https://github.com/moby/moby/blob/master/contrib/dockerd-rootless-setuptool.sh#L349

Which is called if  the `$SYSTEMD` env var is not set; https://github.com/moby/moby/blob/master/contrib/dockerd-rootless-setuptool.sh#L381

Which is detected through these lines; https://github.com/docker/docker-install/blob/master/rootless-install.sh#L62

**Comment by Priyanshu-xcde** [comment]
Thank you @thaJeztah for a reply, and pointing out where specific logs are being printed at.

I'll check the code and see why the setup is failing now, compared to back in Feb with the same Ubuntu-18 VM

**Comment by Priyanshu-xcde** [comment]
@thaJeztah - It took me sometime to circle back to this, and this is my observation:

My changes still work good for latest Ubuntu18 : VERSION="18.04.6 LTS (Bionic Beaver)"

But, I still see issue related to `systemd not detected` for Ubuntu18: VERSION="18.04.5 LTS (Bionic Beaver)"

**Comment by thaJeztah** [comment]
No immediate suggestions, but perhaps @AkihiroSuda has some (he's done a lot more with rootless installations, so perhaps some of these rings a bell)
