### ISSUE TITLE
Could not find records for the current user my_user from /etc/subuid

### ISSUE THREAD

**Issue by frederico-klein** [docker/docker-install#308]
This issue is related to : https://github.com/docker/docker-install/issues/120

I am aware of the instructions that say to add the line 

my_user:100000:65536

to /etc/subuid and to /etc/subgid

However I am using a system with Kerberos authentication have no root access and need to request for this to be done for me. 

I already have 3 entries in this file which are not me like:

    some_user1:100000:65536
    some_user2:165536:65536
    some_user3:231072:65536

Is the line that I should add then 231072+65536:65536 so:

    my_user:296608:65536

I wanted to know what exactly this is doing, if there is a security implication (in which case the sysadmin will likely say no), and if I need to change anything since my authentication is done in a different way. Thank you!

**Comment by AkihiroSuda** [comment]
> Is the line that I should add then 231072+65536:65536 so:
> 
> my_user:296608:65536

Yes.
This means `my_user` can behave as UID 296608 - 362143.
So you will have to ask your admin to confirm that nobody on your system is using UID in this range.

Same applies to GID too.
