### ISSUE TITLE
get.docker.com provides edge channel instead of stable

### ISSUE THREAD

**Issue by mahnunchik** [docker/docker-install#32]
https://get.docker.com/ provides `edge` channel instead of `stable`.

```
DEFAULT_CHANNEL_VALUE="edge"
if [ -z "$CHANNEL" ]; then
	CHANNEL=$DEFAULT_CHANNEL_VALUE
fi
```

**Comment by seemethere** [comment]
As intended. The script isn't meant for production use, it's meant as a convenience to install the latest Docker CE version quickly. If you'd like to lock yourself into the stable channel you can configure it with your package manager.
