### ISSUE TITLE
On Raspberry Pi, BUILD_EXCLUSIVE directive does not match this kernel/arch

### ISSUE THREAD

**Issue by smuda** [docker/docker-install#37]
I'm not sure if this is the right place to file the issue, please redirect me elsewhere if it's wrong.

Anyway, on Raspberry Pi 3, installation of docker from get.docker.com fails with error message:
```
Error! The dkms.conf for this module includes a BUILD_EXCLUSIVE directive
which does not match this kernel/arch. This indicates that it should
not be built.
```
Editing /usr/src/aufs-4.9+20161219/dkms.conf and removing the
line 
```
BUILD_EXCLUSIVE_KERNEL="^4.9.*"
```

then running 
```bash
sudo apt-get remove -y docker-engine
sudo apt-get install -y docker-engine
```

fixes the problem as far as I can see.

Steps to reproduce:
1. Download Raspbian Stretch Lite from https://www.raspberrypi.org/downloads/raspbian/ with release date 2017-09-07 and write to an SD card, fix network etc...
2. Run the following commands:

```bash
sudo apt-get update && sudo apt-get -y upgrade
curl -fsSL get.docker.com -o get-docker.sh
chmod +x get-docker.sh
sudo ./get-docker.sh
```

**Comment by ericcurtin** [comment]
I'm not running Raspbian, so I'm not much help unfortunately.

:worried:

But to me it looks like a problem with "Raspbian Stretch Lite" rather than the installation script.

Hope somebody can help you out!

**Comment by smuda** [comment]
thanks @ericcurtin . As the installation of docker worked with the same version of Raspbian Stretch on the 18th of september, I'd suspect this is something within the dependencies of docker. 

But you're right, I currently don't suspect the installation script. I'll just head over to https://github.com/docker/for-linux instead.

**Comment by smuda** [comment]
In the end, what was missing was installing the linux headers:

`sudo apt-get -y install linux-headers-4.9.0-4-all raspberrypi-kernel-headers`

Should that have been part of the installation script? I really don't know, so I'll leave that to you. 😇

**Comment by ericcurtin** [comment]
I'd open the PR for you @smuda if I could find out where the .deb dependencies are listed in github.

https://download.docker.com/linux/raspbian/dists/stretch/stable/binary-armhf/Packages

If these two packages were listed as dependencies you wouldn't have seen an issue.

I am not a docker employee.

**Comment by peter-hartmann** [comment]
`sudo apt install raspberrypi-kernel-headers`
... worked for me, as described in this post: https://www.raspberrypi.org/forums/viewtopic.php?t=204433

Whereas
`sudo apt-get -y install linux-headers-4.9.0-4-all raspberrypi-kernel-headers`
gave me this error
`E: Unable to locate package linux-headers-4.9.0-4-all`

**Comment by jtmoon79** [comment]
I ran into this problem using Raspberry Pi 2 hardware running Debian 9.6 (stretch).  I'm reposting a few notes in case others run into this and have some brilliant ideas.  Tragically, I couldn't find a workaround in my case.

I didn't use `docker-install`, I followed the instructions at [Get Docker CE for Debian](https://docs.docker.com/install/linux/docker-ce/debian/), but the results probably would have been the same.

I tried a few different permutations of instructions at [Get Docker CE for Debian](https://docs.docker.com/install/linux/docker-ce/debian/) plus the workarounds mentioned in this thread.

I changed the line in ` /usr/src/aufs-4.9+20161219/dkms.conf` to be removed and to be set to `BUILD_EXCLUSIVE_KERNEL=""`.  Didn't help.

I installed `raspberrypi-kernel-headers` but that didn't help.

I tried the workaround mentioned [here](https://blog.alexellis.io/getting-started-with-docker-on-raspberry-pi/) (e.g. try `[arch=arm32v6]` instead of `[arch=armhf]` within `/etc/apt/sources.list.d/docker.list`).  That didn't help.

Error strings I saw (for sake of keyword matching in search engines):

     $ docker run armhf/hello-world
     Illegal instruction

Another one at some other point

      Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
    does not match this kernel/arch.  This indicates that it should not be built.
    Skipped.

Not sure if this is at all related, but I noticed this message during `apt-get install docker-ce` that affects `dkms` (the most likely culprit of this bug)

       serious bugs of dkms (? 2.3-2) <Resolved in some Version>
        b1 - #884658 - dkms: Should really depends on dpkg-dev for dpkg-architecture (Fixed: dkms/2.6.1-2)
       Summary:
        dkms(1 bug)

:-(

**Comment by telmomarques** [comment]
Apparently there's an issue with 18.09.1, but 18.06.1 works fine.

`sudo apt-get remove docker-ce`
`sudo apt-get autoremove`
`sudo apt-get install docker-ce=18.06.1~ce~3-0~raspbian`

I still got the "_BUILD_EXCLUSIVE directive which
does not match this kernel/arch_" error, but the service started fine this time:

```
pi@raspberrypi:~ $ sudo service docker status
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-01-21 23:43:42 GMT; 29s ago
```

Got hint from here:
[https://github.com/docker/for-linux/issues/490#issuecomment-439364798](https://github.com/docker/for-linux/issues/490#issuecomment-439364798)

**Comment by fuglede** [comment]
FWIW, I'm seeing the exact same DKMS errors popping using the 18.06.1 build as suggested by @telmomarques, but the service runs regardless (which it wouldn't when using the most recent version). This is on a Raspberry Pi 1B+:

```
$ uname -a
Linux 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l GNU/Linux

$ sudo apt-get install docker-ce=18.06.1~ce~3-0~raspbian
...
The following additional packages will be installed:
  aufs-dkms aufs-tools cgroupfs-mount dkms linux-headers-3.6-trunk-common linux-headers-3.6-trunk-rpi linux-kbuild-3.6
  linux-kbuild-4.9 pigz
...
Setting up docker-ce (18.06.1~ce~3-0~raspbian) ...
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
[ ok ] Starting Docker: docker.
Setting up linux-headers-3.6-trunk-common (3.6.9-1~experimental.1+rpi7) ...
Setting up cgroupfs-mount (1.3) ...
[ ok ] Mounting cgroupfs hierarchy.
...
Building initial module for 3.6-trunk-rpi
Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
Skipped.
...

$ sudo service docker status
[ ok ] Docker is running.
```
Nevertheless, the `hello-world` image doesn't quite seem to work:
```
$ docker run hello-world
docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.
ERRO[0008] error waiting for container: context canceled
```
As a next step, I tried the solution [outlined here](https://github.com/docker/for-linux/issues/219#issuecomment-375160449). With this, a container runs but exits with no output and no logs. Other containers appear to be failing as well.
```
$ sudo mkdir /sys/fs/cgroup/systemd
$ sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
$ docker run hello-world
```

**Comment by KEINOS** [comment]
F.Y.I @smuda's [comment](https://github.com/docker/docker-install/issues/37#issuecomment-339198643) @peter-hartmann's [comment](https://github.com/docker/docker-install/issues/37#issuecomment-389735912) worked for me! Thanks!!
- RaspberryPi Zero W(ARMv6l) + Stretch Lite ([2019-04-08-raspbian-stretch-lite](https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/))
- The Errors I got:
```bash
Building initial module for 4.19.66+
Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
Skipped.
```
```bash
Building initial module for 4.19.66-v7+
Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
Skipped.
```
- Success Steps To Install Docker(on brand new installed Stretch on RPiZeroW):
```shellsession
$ date -R
Fri, 27 Sep 2019 11:53:38 +0900
$ curl -fsSL https://download.docker.com/linux/raspbian/gpg | sudo apt-key add -
$ # The missing apt of the error
$ sudo apt install raspberrypi-kernel-headers
$ sudo vi /etc/apt/sources.list.d/docker.list
...
$ cat /etc/apt/sources.list.d/docker.list
deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable

$ sudo apt update
...
$ sudo apt-get install docker-ce=18.06.2~ce~3-0~raspbian
...
```
```shellsession
$ sudo docker version
Client:
 Version:           18.06.2-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        6d37f41
 Built:             Sun Feb 10 03:57:32 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       6d37f41
  Built:            Sun Feb 10 03:53:01 2019
  OS/Arch:          linux/arm
  Experimental:     false
$ # 🎉
```
