### ISSUE TITLE
broken mirror due to upstream package resign

### ISSUE THREAD

**Issue by zhangyoufu** [docker/docker-install#379]
A recent upstream package resign breaks the `Aliyun` mirror. It seems that a resign happened at 2023-09-08 and package files were overwritten. Downstream mirrors were not aware of such change and still serves packages files dated 2023-09-05. `apt` reports `Hash Sum mismatch` because the `Release` & `Packages` files expects the new checksum while `.deb` package files were old version.

<details><summary>get-docker.sh --mirror Aliyun (under Debian)</summary>

```
# sh get-docker.sh --mirror Aliyun
# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c install -m 0755 -d /etc/apt/keyrings
+ sh -c curl -fsSL "https://mirrors.aliyun.com/docker-ce/linux/debian/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
+ sh -c chmod a+r /etc/apt/keyrings/docker.gpg
+ sh -c echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://mirrors.aliyun.com/docker-ce/linux/debian bullseye stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin >/dev/null
E: Failed to fetch https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce-cli_24.0.6-1%7edebian.11%7ebullseye_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:a383fcd4f44a64ce402b6e99aece2eb8a4958c9d962d0bf2e6880251205de19812ba259299f880870d1627d1e2b50802adb06da0d52d7fd08b49b989cec23c6c
    - SHA256:3682f04cc7cbeb00e6cf074d629f8b3e03e601986697ba5736a361ee9995b7c7
    - SHA1:40ab285160e1336914c061e75d6baaed8671eb31 [weak]
    - MD5Sum:7e6e0563684df4b790867363c4ac85dd [weak]
    - Filesize:13277902 [weak]
   Hashes of received file:
    - SHA512:90bc1f74c3195e7a0c5b424eae58d8b0291864de3cef0577a1a48886ec34774cbdf7bcf172a193a4e283d911735b3722a0904574d4d93f0c94ab94ee415cdbad
    - SHA256:5f5ac4d3368c8371f29cb00d8bc87ce1504d439f7cd7f3ff82663df7cb7c98bc
    - SHA1:df45ed9cc816a42cf86b4a6a88ed6a92a903b4fa [weak]
    - MD5Sum:4ee59751bc1bfdfe1cbbbece7ae21e68 [weak]
    - Filesize:13277902 [weak]
   Last modification reported: Tue, 05 Sep 2023 19:27:35 +0000
E: Failed to fetch https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce_24.0.6-1%7edebian.11%7ebullseye_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:f01a1948392192f32cb9d88e2d61dc7d44a98755b471c5ed7857a1660d1653cb6dbd5f665589aac185c1745e538583102ce61c7b5597175ada04326643028b37
    - SHA256:b6666acab70f44231f2e65279a2f0d97be9e3c6fecbf16094135aea961090456
    - SHA1:7c33fc7731f6665e54a35eab8b84f71a6de791b8 [weak]
    - MD5Sum:0e96a1aaf96fc4c30904109bd372a20f [weak]
    - Filesize:22569694 [weak]
   Hashes of received file:
    - SHA512:253335d5b6b1afc56ed4f07d2d87abbe641cf4270a9edafb095d4b9008529ccdef9bef37fa8b83c76dbd65d7c2d6e579e2de66400cbf3b45a3851d8f1871f94b
    - SHA256:7714f91061831bb51b2c09edd05d50457809bf182361380294f11ec46093486f
    - SHA1:e3900078a0eecd8ac1d3ffc2917ed6b8efda1e45 [weak]
    - MD5Sum:15fa9f8d44cb504c372d26ea3062c486 [weak]
    - Filesize:22569694 [weak]
   Last modification reported: Tue, 05 Sep 2023 19:27:36 +0000
E: Failed to fetch https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce-rootless-extras_24.0.6-1%7edebian.11%7ebullseye_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:39a8659d013809d99efd62011bd573d422973f623d317ae03382a6b538b94f992e6062f2893042d5441765ee8d0c267c86b0d65db3072b7cd30f7cf517c37704
    - SHA256:9ffb9bcdd5ca0043137a2c6dc366263ed0c652a483db4873586166c0b31dbb2f
    - SHA1:3c261bdf98bf1ca02b341048526c8d0c245b9e75 [weak]
    - MD5Sum:d69201484f1635ff7f519efa21aef467 [weak]
    - Filesize:9029160 [weak]
   Hashes of received file:
    - SHA512:f9a0749e921e63b1d54d9203eaa8267131d6cf71d48f42383e9cdbe704814ee00679902c19ef4aac43047140463f8b3ce40448208583715316c93e19a5cd1e3f
    - SHA256:a5d48dde3df4086b7cb6967026282a4b4d5f396a05a8c4f61b209e07c94a50aa
    - SHA1:d3a3c269623736b5cc2fa48a7e1e654b522ea0e3 [weak]
    - MD5Sum:71163a30906899211137b7e31891566b [weak]
    - Filesize:9029160 [weak]
   Last modification reported: Tue, 05 Sep 2023 19:27:36 +0000
E: Failed to fetch https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bullseye/pool/stable/amd64/docker-compose-plugin_2.21.0-1%7edebian.11%7ebullseye_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:4cc52e486283b6e0da4ae610f58409700667ad2aa1610d942c6eef7046d432f5c8203044aa7b6b7d8e25c45ea3aeabb5a758f221753f3362f59a3c28c559194b
    - SHA256:aad6c0ae69e19d67b042af2d50aa2fb0507929f2ab8976fc5e89c515225024a5
    - SHA1:38640a84d3f1f8a326f50398b265e2de0c16d7fd [weak]
    - MD5Sum:2d0388b5d043922b9e399cfe42b18039 [weak]
    - Filesize:11941178 [weak]
   Hashes of received file:
    - SHA512:c67d91bc14a5f35bd789dbd5302da88cf232be6619b21dfecda6de642dfd2939894bc90e4bf5ab321a67e03368911f6e333d2b8d3abfe8b207906339913ad323
    - SHA256:f75983661dd69d4ef5d3487b769833f21c1b5ee0bfdac9a83e6a9bdabcd27b15
    - SHA1:1e7515f335d4d0bfcbd4ef16f18e5dc884331f57 [weak]
    - MD5Sum:5e4966c22a7b4cc0577c392f7fc71f22 [weak]
    - Filesize:11941178 [weak]
   Last modification reported: Tue, 05 Sep 2023 19:27:37 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
</details>

**Comment by zhangyoufu** [comment]
@thaJeztah Since you are familiar with the packaging and releasing procedure, may I have your attention here?

China does not have reliable connection to CloudFront edge servers, so domestic mirrors are important to Docker users in mainland China. Until today, some downstream mirror of https://download.docker.com in mainland China still ran into issue like this.

AFAIK download.docker.com is hosted by AWS S3 + Cloudfront. The directory listing (index.html) is generated before uploading to S3 bucket.

It's somehow tedious and unreliable to crawl and parse directory listing from each directory and determine which file was updated since last sync:
1. Some file disagree on mtime shown on `index.html` and Last-Modified HTTP header (Last-Modified is a S3 system property and is not allowed to be modified by user)
2. Some file have zero size shown on `index.html`, possibly due to btrfs dedup/reflink and calling `du` without `--apparent-size`, according to https://github.com/moby/moby/blob/39bcaee47b8a284a46b761afe218ba7deda0d482/hack/make/generate-index-listing#L50

To make downstream mirror synchronizing more reliable and efficient, and to avoid issues like this in future, is it possible to
1. provide read-only access to the AWS S3 bucket behind download.docker.com upon request
  According to https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status, `clojars`/`julia-releases`/`kicad`/`nix`/`saltstack` are synchronized in this way.
2. host an `ls-lR.gz` file in the root directory of download.docker.com

**Comment by thaJeztah** [comment]
Heh, yes, syncing bucket is a _big pain_ altogether. So the fun fact is that our pipeline has to perform similar steps during releases (we use a "ring-buffer" of buckets to which we deploy; those buckets are synced with the "live" bucket; updated with new packages; verified, and then moved over to the "live domain". Amazon's tools aren't "great" for this (and some 3rd party tools, like `rsync`) also ran into issues.

We had a call recently with some Amazon solution architects to look at possible alternatives, and @neersighted is looking into those; perhaps some of those solutions _could_ also be used by external consumers. I'll let @neersighted answer that, as he may have better insight into that (as he's more familiar with the suggested alternatives).

**Comment by zhangyoufu** [comment]
Here is a list of `the backing bucket (which, technically is already public)` I found:
- docker-release-blue-prod
- docker-release-cyan-prod
- docker-release-emerald-prod
- docker-release-green-prod
- docker-release-orange-prod
- docker-release-purple-prod
- docker-release-red-prod
- docker-release-yellow-prod

I wonder if there is any way to determine which bucket is the **current** version of `download.docker.com`.

---

IMHO, a bucket ring for software distribution is a disaster. Rollback shouldn't be implemented as just switching the backing bucket.

For an APT repository, APT understands a field called `Phased-Update-Percentage` (an integer between 0 and 100) which could be used to control the rollout of a new version precisely and reduce damage when serious bug was introduced. When a new version needs to be retracted, remove corresponding binary/source package files and metadata from `Packages`/`Release` files. When the new version is ready to ship again, it should not be re-published under the same `Version`. (a user may have already installed that version thus apt won't upgrade)

**Comment by thaJeztah** [comment]
Rollbacks are a very exceptional case (and before this incident were never executed); the main use for the bucket ring is to provide environments for verifying state before publishing and to cut down time to deploy to download.docker.com (deploying releases to s3 takes multiple hours).

**Comment by neersighted** [comment]
With regard to rollback, it's intended to be used for metadata as that is normally the "tricky" and "lossy" thing, which is seamless and has been done in the past. We've never had to roll back packages before, but there was a rather extraordinary situation involving interesting behavior between the AWS CLI and s3cmd (too long to get into here) and it was "less bad" than causing 404s for 24.0.6.

With regard to those backing buckets, they are not "correct" and I would not suggest syncing from them, as the repository is not "complete" without being viewed through CloudFront.

They are not currently request-payer, but they may become so if traffic to them becomes an issue.

**Comment by iBug** [comment]
According to <https://github.com/tuna/issues/issues?q=is%3Aissue+docker-ce>, `docker-ce` is about the most frequently broken repository on Chinese mirror sites. It would be nice if Docker, Inc. offers a better sync method so that downstream mirrors do not have to work around every problem brought by the HTML directory listing.
