### ISSUE TITLE
aarch64-fedora-27 support

### ISSUE THREAD

**Issue by ericcurtin** [docker/docker-install#40]
Fedora is about to release SBC images (aarch64) for the following devices:

Pine64 (all variants)
Raspberry Pi 3 (64 bit mode)
96boards HiKey
96boards Dragonboard 410c
ARM Juno

https://fedoraproject.org/wiki/Changes/aarch64SBCImages
https://fedoraproject.org/wiki/Releases/27/ChangeSet#aarch64_SBC_.28Single_Board_Computer.29_Disk_Images
https://bugzilla.redhat.com/show_bug.cgi?id=1479254

Before you get inundated with requests for this, the aarch64-fedora-27 platform....

It would be more beneficial to the community than aarch64-ubuntu-xenial as it will run on rpi3s and such very shortly.

Upto now I have been using the version of docker that comes in the repo of:

http://download.opensuse.org/ports/aarch64/distribution/leap/42.2/appliances/openSUSE-Leap42.2-ARM-XFCE-raspberrypi3.aarch64.raw.xz

But it's old and buggy and not packaged by you guys. An aarch64-fedora-27 rpm packaged by you guys would be great.

Btw, I'm happy to help if you need a hand

**Comment by seemethere** [comment]
ping @friism

**Comment by friism** [comment]
@ericcurtin thanks for opening this and for caring about running Docker on Fedora on ARM. We're a little busy prepping for DockerCon and a few other things, but we'll take a look at this over the coming months.

**Comment by ericcurtin** [comment]
@friism no problem...

:grinning:

I care because a couple of rpi3's running Ubuntu 14.04/16.04 dockers are our main test devices for the aarch64 flavour of our software!

Ubuntu 14.04 and 16.04 isn't supported natively on rpi3.

It would be so helpful if there was aarch64-fedora-27 support.

Anyway best of luck with DockerCon!

**Comment by ericcurtin** [comment]
I see this is unlikely until 17.12.0-ce

https://github.com/docker/for-linux/issues/143

I guess it's hard for you guys to commit to supporting every platform. I'm not really a die hard supporter of any distro, would have been nice to see docker supported on some linux distro that supports rpi3 in aarch64 mode

**Comment by ericcurtin** [comment]
Fedora released these anyway:

https://fedoraproject.org/wiki/Architectures/ARM/Raspberry_Pi

See heading "Raspberry Pi 3 aarch64 support"

Might get to building an aarch64 .rpm over Christmas sometime. If I build a aarch64 rpm and submitted a PR similar to this one:

https://github.com/docker/docker-ce-packaging/pull/59

Would it be accepted? And would I get a fedora 27 aarch64 rpm in the next release of docker?

**Comment by seemethere** [comment]
Relates to https://github.com/docker/docker-ce-packaging/pull/71

**Comment by philipmather** [comment]
Hello, I'd be one of those looking to inundate you for aarch64-fedora-27 please!

**Comment by seemethere** [comment]
Added as of #58
