### ISSUE TITLE
Could python be removed to reduce the install footprint?

### ISSUE THREAD

**Issue by michaelbarton** [docker/docker-install#43]
Please excuse my ignorance if this is a stupid issue request. My understanding is that docker is written in go, so I am curious as to why python installed by this script? I'm not using python so having it installed via `python-software-properties` or `software-properties-common` to use docker feels a little superfluous.

I've tried to google search if docker has any python dependencies before opening this issue, but I couldn't see any.

**Comment by seemethere** [comment]
Yup I'm not entirely sure what it's being used for either. Removed it in #51 

Closed with #51
