### ISSUE TITLE
Docker Image for Sitespeed goes missing!!

### ISSUE THREAD

**Issue by ganeshmuralidhar** [docker/docker-install#50]
Hi,

I started using the docker version on sitespeed and is able to run tests followed by proper reporting.
I started facing a weird issue where on one particular machine, I pull the docker image using

docker pull sitespeedio/sitespeed.io

and i execute a test. So far so good, after few minutes when I execute another test, i get an error saying 'Unable to find image 'sitespeedio/sitespeed.io:latest' locally' and the image gets downloaded again.

When i re-checked the same by looking at docker images on my host, i see that the sitespeed image went missing. I tried multiple ways to restore it by composing a tar file one a different host and extracting it here. But after few mins the image just goes missing and i couldn't find it any where.

I have to do a docker pull everytime i need to use sitespeed. Any pointers here please?

I am sure this is nothing to do with Sitespeed as the same image is pulled and used forever on other hosts. I cannot any difference in the machines too. Please assist!

**Comment by seemethere** [comment]
Not related to this particular repo, I'd suggest posting this issue in https://github.com/docker/for-linux
