### ISSUE TITLE
how to select docker version like  17.12 ce when use this script?

### ISSUE THREAD

**Issue by xiaopeng163** [docker/docker-install#61]
Thanks.

**Comment by MAGICCC** [comment]
You can set the environment variable of `$CHANNEL` to `stable` so https://get.docker.com/ will install the stable version of docker.
Using the script isn't best practice, even a dev [said](https://github.com/docker/docker-install/issues/32) that the script isn't meant for production use, it's meant as a convenience to install the latest Docker CE version quickly, which includes edge versions.

TL;DR
```curl -sSL https://get.docker.com/ | CHANNEL=stable sh```

**Comment by xiaopeng163** [comment]
so, through this script, I can't choose the older version of CE, like 17.03,yes?

**Comment by MAGICCC** [comment]
No, why would you install older versions of docker. They can include security vulnerabilities

**Comment by xiaopeng163** [comment]
thanks for your reply.

I write some labs for docker and want to keep it versioned, so I want to use a fixed docker version.

I provided a vagrant host with docker auto installed, but with this script, I can't control the docker version installed on the vagrant host, it will always install the lastest.

https://github.com/xiaopeng163/docker-k8s-lab/tree/master/lab/docker/single-node/vagrant-centos7

**Comment by xiaopeng163** [comment]
anyway, I will close the issue, thanks for your information

**Comment by seemethere** [comment]
@xiaopeng163 This has been added in as of #62

**Comment by xiaopeng163** [comment]
oh, thanks for your work
