### ISSUE TITLE
Edge does not install on ubuntu 18.04

### ISSUE THREAD

**Issue by gbgbgbg** [docker/docker-install#72]
user@ubuntu:~$ sh get-docker.sh 
# Executing docker install script, commit: 36b78b2
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sudo -E sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic edge" > /etc/apt/sources.list.d/docker.list
+ [ ubuntu = debian ]
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
E: Package 'docker-ce' has no installation candidate

**Comment by seemethere** [comment]
18.05 will be the first release with Ubuntu Bionic support. The first rc was released yesterday so expect the full release to come in the upcoming weeks.

**Comment by gbgbgbg** [comment]
perhaps the '-bionic' lines should be removed from the script before support is available?

**Comment by seemethere** [comment]
Perhaps, we're currently in the process of trying to deprecate the `SUPPORT_MAP` altogether and come up with a better more automated solution.

**Comment by seemethere** [comment]
In the mean time, to use the script to install on Ubuntu Bionic I'd suggest:
```
curl -fsSL get.docker.com | CHANNEL=test sh
```

**Comment by gbgbgbg** [comment]
Thanks!

**Comment by seemethere** [comment]
Closing this since packages are now available with:

```
curl -fsSL get.docker.com | sh
```
