### ISSUE TITLE
Remove support for Debian Wheeze

### ISSUE THREAD

**Issue by delfer** [docker/docker-install#73]
Docker does not support Debian 7 Wheeze:

> Your Linux kernel version 3.2.0-4-amd64 is not supported for running docker. Please upgrade your kernel to 3.10.0 or newer.

Checked on DigitalOcean's Debian 7.11 x64

Please, remove support from script.

**Comment by seemethere** [comment]
Debian Wheezy support will be removed once it reaches EOL on June 1, 2018

Related: https://github.com/docker/docker-ce-packaging/pull/108
