### ISSUE TITLE
Check the permission of script when download

### ISSUE THREAD

**Issue by 1juandiaz** [docker/docker-install#75]
Hi there! 
I think i found a issue, maybe you need to check that. 
When you did a curl and download the file, this one dont have permission of execute the script. So, you can add ```bash chmod 777``` to execute file or upload again the file with the correct permission.
I hope this help you . Be docker! Regards

**Comment by seemethere** [comment]
Yup! Scripts that are downloaded from the web are usually marked non-executable by default!

A more common way to do this is

```
chmod +x myscript
```

Thanks!
