### ISSUE TITLE
update the default channel in get.docker.com  

### ISSUE THREAD

**Issue by mataneja** [docker/docker-install#77]
Currently, get.docker.com sets the default channel to edge

> DEFAULT_CHANNEL_VALUE="edge"

If we continue to plan to use this script, it would be useful to point this to Stable/Nightly instead

**Comment by mataneja** [comment]
A lot of people continue to use this script for production deployments despite our Notice to the contrary. Perhaps, best to have 2 versions of this script or make the channel a dynamic argument on the CLI. This will let people use the script and select stable channel if deploying to prod.

**Comment by MAGICCC** [comment]
Well you can use `curl -sSL https://get.docker.com/ | CHANNEL=stable sh`
