### ISSUE TITLE
Ubuntu 12.04 LTS (Precise) denpendency issue.

### ISSUE THREAD

**Issue by SiqingYu** [docker/docker-install#78]
When trying to install docker-ce package:
```shell
sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
```

But docker-ce depends on a later version of libdevmapper.
```
The following packages have unmet dependencies:
 docker-ce : Depends: libdevmapper1.02.1 (>= 2:1.02.63) but 2:1.02.48-4ubuntu7 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Manually installing [libdevmappe1.02](https://packages.debian.org/wheezy/libdevmapper1.02.1) and [dmsetup](https://packages.debian.org/wheezy/dmsetup) from Debian wheezy release solves the problem.

**Comment by seemethere** [comment]
Ubuntu 12.04 is not within support and we do not release packages for it anymore. This is expected behavior.
